// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/assesment-request.tsx";
import * as $3 from "./routes/autism-assessment-and-formulation.tsx";
import * as $4 from "./routes/contact.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/staff/claire-madeira.tsx";
import * as $7 from "./routes/staff/georgie-bainbridge.tsx";
import * as $$0 from "./islands/AfterAssesmentAccordion.tsx";
import * as $$1 from "./islands/AssesmentAccordion.tsx";
import * as $$2 from "./islands/AssesmentForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/assesment-request.tsx": $2,
    "./routes/autism-assessment-and-formulation.tsx": $3,
    "./routes/contact.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/staff/claire-madeira.tsx": $6,
    "./routes/staff/georgie-bainbridge.tsx": $7,
  },
  islands: {
    "./islands/AfterAssesmentAccordion.tsx": $$0,
    "./islands/AssesmentAccordion.tsx": $$1,
    "./islands/AssesmentForm.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
